env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  'require-jsdoc': off,
  'max-len': off,
  'no-unused-vars': off,
  '@typescript-eslint/no-unused-vars': ['error'],
  'object-curly-spacing': ['error', 'always'],
  'indent': [
    'error', 2, {
      'CallExpression': {
        'arguments': 2,
      },
      'FunctionDeclaration': {
        'body': 1,
        'parameters': 2,
      },
      'FunctionExpression': {
        'body': 1,
        'parameters': 2,
      },
      'MemberExpression': 1,
      'ObjectExpression': 1,
      'SwitchCase': 1,
      'ignoredNodes': [
        'ConditionalExpression',
      ],
    },
  ],
}
